package test.tokopedia.newsapp.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import test.tokopedia.newsapp.data.SourceData;

import test.tokopedia.newsapp.data.SourceDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sourceDataDaoConfig;

    private final SourceDataDao sourceDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sourceDataDaoConfig = daoConfigMap.get(SourceDataDao.class).clone();
        sourceDataDaoConfig.initIdentityScope(type);

        sourceDataDao = new SourceDataDao(sourceDataDaoConfig, this);

        registerDao(SourceData.class, sourceDataDao);
    }
    
    public void clear() {
        sourceDataDaoConfig.clearIdentityScope();
    }

    public SourceDataDao getSourceDataDao() {
        return sourceDataDao;
    }

}
